# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - name: Install build deps
        run: |
          npm install -g @angular/cli
          npm install -g firebase-tools
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Build jonzlotnikca
        run: |
          cd jonzlotnikca
          npm install
          ng build --prod
          cd ..
      - name: Deployment
        run: |
          cd jonzlotnikca
          firebase use --add "jonzlotnikca"
          firebase deploy --only hosting
          cd ..
          
          
